name: Generate snmp exporter configuration

on:
  push:
    paths-ignore:
    - 'config-generator/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository_owner	 }}/snmp-config-generator

jobs:
  generate-config:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run generator
        run: |
          docker run -v "$PWD:/config" -w /config \
            "${REGISTRY}/${IMAGE_NAME,,}:latest" \
            generate -m /mibs

      - name: Upload generated configuration as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snmp.yml
          path: snmp.yml
